x-blockchain-env: &blockchain-env
    SEPOLIA_RPC: ${SEPOLIA_RPC}
    PRIVATE_KEY: ${PRIVATE_KEY}
    REGISTRY: ${REGISTRY}
    PRIVATE_KEY_2: ${PRIVATE_KEY_2}
    REVENUE: ${REVENUE}
    PINATA_API_KEY: ${PINATA_API_KEY}
    PINATA_API_SECRET: ${PINATA_API_SECRET}
    PINATA_JWT_TOKEN: ${PINATA_JWT_TOKEN}

services:
    db:
        image: docker.io/library/postgres:18.1-alpine3.23
        container_name: blockchain-db
        ports:
            - "5433:5433"
        environment:
            POSTGRES_USER: blockchain-db
            POSTGRES_PASSWORD: TP075164
            POSTGRES_DB: db
            PGPORT: 5433
        command: postgres -p 5433
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U blockchain-db -d db -p 5433"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        image: docker.io/library/golang:1.25.5-trixie
        working_dir: /app
        volumes:
            - ./backend:/app
        environment:
            <<: *blockchain-env
            DB_URL: postgres://blockchain-db:TP075164@db:5433/db?sslmode=disable
        depends_on:
            - db
        command: /bin/sh -c "go mod download && go run main.go"
        ports:
            - "3000:3000"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "5173:5173"
        depends_on:
            backend:
                condition: service_started

volumes:
    postgres_data:
