services:
    blockchain-db:
        image: docker.io/library/postgres:18
        container_name: blockchain-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: blockchain-db
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U blockchain-db -d db"]
            interval: 5s
            timeout: 5s
            retries: 5
